### ISSUE TITLE
As a scholar I want to view the EYE Desmet Paper archive in the MS

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#293]
This issue consists of:

**-Importing the Excel file that contains the metadata of all the digitized paper collection of Desmet business archive**

- [ ] Register the collection in the CKAN collection repository

- [ ] Using the MSDataManager CSV importer, probably use the to-be-created dataConverter

**-Link the metadata to the image files**

- [ ] Make sure the image files are viewable (setup IIIF) and are referable (from the metadata)

**-Integrating the experimental OCR to this paper collection to the records**

- [ ] Make sure the OCR files are provided (separate file?, annotation?, index?) and are referable (from the metadata)

**Comment by jblom** [comment]
"Using the MSDataManager CSV importer, probably use the to-be-created dataConverter" is the only task not done. The import was done separately with a script.

I suggest closing this issue and possibly creating a new issue about making sure that all CKAN collections that should show up in the collection selector are properly imported via the importing pipeline (however I would also suggest to wait with this, since it is an issue that will probably linger for a while).

**Comment by lilimelgar** [comment]
I entered what you suggest as a new issue (to not forget), I let it in the New issues (to be placed in the sprint planning then)
