### ISSUE TITLE
As a scholar I want to save my search queries in the MS workspace to re-visit the search results for this query later

### ISSUE THREAD

**Issue by jblom** [CLARIAH/wp5_mediasuite#336]
Saved queries can be later used for various components. TODO add more examples

**Comment by lilimelgar** [comment]
@jblom is this the same as #10? shall we close that one?

**Comment by lilimelgar** [comment]
Good example: Scopus database, medical databases (Ovid), Web of Science.

**Comment by jblom** [comment]
The mechanism for saving queries works now. At the moment it can only be used from the single search.

@lilimelgar @roelandordelman I suggest formulating a new issue/story for saving/loading queries from the comparative search (which should mostly be about UX).

**Comment by lilimelgar** [comment]
Tested in Master (March 28) with:
-B&G collection
-EYE Desmet films and posters
-Open Beelden (EYE and B&G)
-Newspapers (did not work -issues with index)
-OH: the saved query was not replayed (entered as new issue #349)

These ToDos emerged from testing (we can evaluate later if adding them as new issues to this epic, or if they need a separate epic):

- [ ] **Adding more information about the parameters to the query details in the workspace**The parameters that are indicated in the query (search string, field cluster, date field + range, filter from facet) are properly remembered when the query is replayed :), however, these parameters are not shown in the details of the saved query (I added my parameters in the title as a solution for remembering them myself as a user -the query does):
![screen shot 2018-03-27 at 11 09 46](https://user-images.githubusercontent.com/8133228/37957983-91e906cc-31af-11e8-88a5-b8d174d3462c.png)

- [ ] **Saving favourite aggregations/facet views to your work space**. When a custom facet is added (e.g., "colour") to the query, and a filter is used from that facet (e.g., "zwart/wit") (see image 1), and the query is saved and replayed, the results bring back the correct filter (see "zwart/wit" in the image), but the facet itself is not remembered (see image 2).
Image 1: 
![screen shot 2018-03-27 at 11 20 40](https://user-images.githubusercontent.com/8133228/37958479-ec5ffd80-31b0-11e8-9b1b-7c5721dcd750.png)
Image 2:
![screen shot 2018-03-27 at 11 20 17](https://user-images.githubusercontent.com/8133228/37958487-f365b58e-31b0-11e8-970f-701fd6163313.png)

- [ ] Pending testing when issue #144 (adding custom field clusters) is implemented, probably we will need saving favourite field clusters to the work space.

**Comment by lilimelgar** [comment]
Tested in master (March 28) with all collections except:
-KB newspapers (not available)

All correct in replaying, except for the OH collection (issue added #349).

New issues emerge from testing (pending to evaluate if adding them as new issues/epics)

- [ ] Adding details to the query list in the work space. The parameters are all "saved" but the user does not see which parameters where used, unless s(he) adds them to the title of the query.
![screen shot 2018-03-27 at 11 05 02](https://user-images.githubusercontent.com/8133228/37961335-44874138-31b8-11e8-8577-113b52dd572a.png)

- [ ] **Saving favourite aggregations/facet views to your work space**. At this moment, if a user creates a new facet, and selects one term inside that facet in the filter, saving the query, the value used for filter is remembered (image 2) but not the facet itself (image 1)
-Image 1
![screen shot 2018-03-27 at 11 20 40](https://user-images.githubusercontent.com/8133228/37961448-9b40915a-31b8-11e8-9be6-75c0396bc451.png)
-Image 2
![screen shot 2018-03-27 at 11 20 17](https://user-images.githubusercontent.com/8133228/37961457-a1f0076a-31b8-11e8-8419-b5796734826d.png)

**Comment by lilimelgar** [comment]
This Epic is mostly done, users loved it! Tested on production version during preparatory workshop for summer school.
