### ISSUE TITLE
As a developer I need to set up an internal cloud infrastructure for ASR processing of audiovisual items from the archive

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/wp5_mediasuite#504]
## Prerequisites:

- Understanding the use of Docker, docker compose, docker-swarm (and for comparison Kubernetes).
- Global understanding of the Kaldi-asr software and the derived Kaldi-NL repository.
- Understanding the Kaldi_NL BGWorker package (providing a worker management queue pattern).
- Basic MySQL/MariaDB Database management tasks.
- Understanding the use of Jupyter notebooks and Plotly, in combination with Google sites for analysis.
- Understanding the basics of the Python scripts that manage the archive downloaders for low res.

## Tasks:
- [x] Install SQL database
- [x] Load data from SurfSara environment (120GB, ~2 days)
- [x] Manage cluster (VMWare based servers)
- [x] Manager worker cluster (using Kubernetes or Docker swarm).
- [x] Manage Docker containers and their settings.
- [ ] Provide audio data (using the already built scripts).
- [ ] (assigned to: Mari) Provide overall statistics on percentages of radio/television material processed/to be processed.
- [ ] Create necessary documentation on the wiki of the github project.

## Acceptance criteria:
- [ ] ASR site shows live progress, charts etc.
- [ ] Worker queue is managed and can be configured (set priorities, etc.).
- [ ] Program package manager is working properly.
- [ ] Worker cluster is providing scalable solution.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/asr-av-archive #6](https://github.com/beeldengeluid/asr-av-archive/issues/6) via [**ZenHub**](https://www.zenhub.com/)
