### ISSUE TITLE
As an architect I need to choose the best solution for running workers in containers within the currecnt IT infrastructure.

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/wp5_mediasuite#505]
The current setup within Sound and Vision is a VMWare/vCenter based solution, providing us with VM's that are connected to the (internal) server network (having Bond villain names).

The server OS is RHEL 7.

The ASR cluster contains a Database server (MySQL/MariaDB), Fileserver and 2 Workers (Kaldi_NL & BGConfig). 

### Networking
See Docker reference architecture docs [here](http://success.docker.com/article/networking) and [here](https://docs.docker.com/network/)

### Comparison
Two possible solutions are compared:
* https://kubernetes.io/docs/setup/minikube/
* https://docs.docker.com/engine/swarm/

Google for 'Kubernetes  vs docker swarm' or something like that...

Docker swarm seems to be the best fit for now.

### Current solution
* A docker swarm was created on the fatimablush.beeldengeluid.nl (Swarm manager). 
* Dominopetanchi,beeldengeluid.nl has joined the swarm. 
* Database server and fileserver aren't part of the swarm, so they need to be connected through their host networks. 

#### To do's
* The worker services need to be started from within the container.

## Done
- [x] Docker containers and [services](https://docs.docker.com/engine/swarm/services/) must be started from within the swarm manager. (deploy with ```docker service create``` and ```docker service scale=```
* Setup a local registry (using TLS certificates) that enables a docker service to be created that can be run on other swarm nodes using `docker service create` and `docker stack`.

## Tasks
- [x] Choose a network model that fits the provided solution. 
- [x] Modify the container, build it.
- [x] run the actual container and test it. (although the service containers were shut down. This must be studied).
- [x] Limit the resources the containers will use. https://docs.docker.com/config/containers/resource_constraints/
- [x] Discuss the solution with system administrators. Ask for more resources.

**Comment by wmelder** [comment]
Closing this issue now and save the story's documentation to the beeldengeluid/asr-av-archive repository wiki.
