### ISSUE TITLE
As a developer I need to adapt the 'old' ASR workflow, so that a list of documentaires can be ASR'ed.

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/wp5_mediasuite#507]
## Tasks
- [x]  List of 148 documentaries about WOII
- [x] Prepare the downloader to act on a given list of programID's
- [x] Download from the lowres, prepare 'program packages'
- [x] Send the audio to the 'old' recognizer setup
- [x] Collect the results (bundle carrier results files with programs)
- [-] Add the new results to the NISV colelction in the Media Suite. Might  reconsider this, since the ASR results for crossewt are not processed like all the others (added to the BG_ASR_Admin database).

## Acceptance criteria
* Complete list processed and send to Susan Hogervorst.

## Issues
* The programs with the following programIDs were not in the index:

5289290@program
5283526@program
5289290@program
5290662@program
5292180@program
